#!/bin/sh
# PreToolUse hook: block edits to the public/ directory.
# public/ is generated by `node build.js` — editing it directly is always wrong.
# Receives a JSON object on stdin with tool_name and tool_input.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | node -e "
  const d = JSON.parse(require('fs').readFileSync('/dev/stdin','utf8'));
  process.stdout.write(d.tool_input && d.tool_input.file_path || '');
" 2>/dev/null)

case "$FILE_PATH" in
  */public/*)
    node -e "
      process.stdout.write(JSON.stringify({
        hookSpecificOutput: {
          hookEventName: 'PreToolUse',
          permissionDecision: 'deny',
          permissionDecisionReason: 'public/ is generated by \`node build.js\` — edit the source files (index.html, utils.js) instead and rebuild.'
        }
      }));
    "
    exit 0
    ;;
esac

exit 0
